version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Location of the package manifests
    schedule:
      interval: "weekly" # Options: "daily", "weekly", "monthly"
    open-pull-requests-limit: 19
    rebase-strategy: "auto"
